import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Inter } from "next/font/google";
import React from "react";
import { ILayoutProps } from "@/types/layoutProps";

const InterFont = Inter({ subsets: ["latin"] });

const snagFont = localFont({
  src: "../fonts/snagajob-nib-bold.woff2",
  variable: "--font-snag",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ILayoutProps) {
  return (
    <html lang="en">
      <body className={`${snagFont.variable} ${InterFont.className}`}>
        {children}
      </body>
    </html>
  );
}
